version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - застосунку
  - застосунок
  - контейнеризації
  - контенту
  - налаштунками
  - нашталт
  - репозиторій
  - репозиторію
ignoreWords: []
import: []
language: en,uk
