# Generated by Django 4.1.6 on 2023-03-12 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
