# Generated by Django 4.0.5 on 2022-08-25 18:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_lots_comments_bids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lots',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
