# Generated by Django 4.0.5 on 2022-08-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_lots_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lots',
            name='category',
            field=models.ManyToManyField(blank=True, to='auctions.category'),
        ),
    ]
