# Generated by Django 4.0.5 on 2022-08-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_lots_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='lots',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
